import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import SVR 
X = np.linspace(0, 10, 100)
y = np.sin(X)
X = X.reshape(-1, 1)
svr_linear = SVR(kernel="linear", C=1000, gamma='scale', epsilon=0.1)
svr_rbf = SVR(kernel="rbf", C=1000, gamma='scale', epsilon=0.1)
svr_linear.fit(X, y)
svr_rbf.fit(X, y)
y_pred_linear = svr_linear.predict(X)
y_pred_rbf = svr_rbf.predict(X)
plt.figure(figsize=(8, 6))
plt.scatter(X, y, color="darkorange", label="Original data")
plt.plot(X, y_pred_linear, color="navy", lw=2, label="SVR (Linear Kernel)")
plt.title("SVR with Linear Kernel on Sine Curve")
plt.xlabel("X")
plt.ylabel("y")
plt.legend()
plt.grid(True)
plt.show()
plt.figure(figsize=(8, 6))
plt.scatter(X, y, color="darkorange", label="Original data")
plt.plot(X, y_pred_rbf, color="green", lw=2, label="SVR (RBF Kernel)")
plt.title("SVR with RBF Kernel on Sine Curve")
plt.xlabel("X")
plt.ylabel("y")
plt.legend()
plt.grid(True)
Plt.show()
